# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qsom.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from ui.uiutils import ParamLineEdit

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QSom(object):
    def setupUi(self, QSom):
        QSom.setObjectName(_fromUtf8("QSom"))
        QSom.resize(800, 600)
        QSom.setMinimumSize(QtCore.QSize(800, 600))
        QSom.setMaximumSize(QtCore.QSize(800, 600))
        QSom.setMouseTracking(False)
        self.horizontalLayoutWidget = QtGui.QWidget(QSom)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 451))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayoutMain = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutMain.setObjectName(_fromUtf8("horizontalLayoutMain"))
        self.menuVLayout = QtGui.QVBoxLayout()
        self.menuVLayout.setObjectName(_fromUtf8("menuVLayout"))
        self.groupBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.alfaLabel = QtGui.QLabel(self.groupBox)
        self.alfaLabel.setMinimumSize(QtCore.QSize(150, 22))
        self.alfaLabel.setObjectName(_fromUtf8("alfaLabel"))
        self.horizontalLayout.addWidget(self.alfaLabel)
        self.alfaLEdit = ParamLineEdit(self.groupBox)
        self.alfaLEdit.setMinimumSize(QtCore.QSize(250, 22))
        self.alfaLEdit.setObjectName(_fromUtf8("alfaLEdit"))
        self.horizontalLayout.addWidget(self.alfaLEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gammaZeroLabel = QtGui.QLabel(self.groupBox)
        self.gammaZeroLabel.setMinimumSize(QtCore.QSize(150, 22))
        self.gammaZeroLabel.setObjectName(_fromUtf8("gammaZeroLabel"))
        self.horizontalLayout_2.addWidget(self.gammaZeroLabel)
        self.gammaZeroLEdit = ParamLineEdit(self.groupBox)
        self.gammaZeroLEdit.setMinimumSize(QtCore.QSize(250, 22))
        self.gammaZeroLEdit.setObjectName(_fromUtf8("gammaZeroLEdit"))
        self.horizontalLayout_2.addWidget(self.gammaZeroLEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sigmaZeroLabel = QtGui.QLabel(self.groupBox)
        self.sigmaZeroLabel.setMinimumSize(QtCore.QSize(150, 22))
        self.sigmaZeroLabel.setObjectName(_fromUtf8("sigmaZeroLabel"))
        self.horizontalLayout_3.addWidget(self.sigmaZeroLabel)
        self.sigmaZeroLEdit = ParamLineEdit(self.groupBox)
        self.sigmaZeroLEdit.setMinimumSize(QtCore.QSize(250, 22))
        self.sigmaZeroLEdit.setObjectName(_fromUtf8("sigmaZeroLEdit"))
        self.horizontalLayout_3.addWidget(self.sigmaZeroLEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.networkSizeLabel = QtGui.QLabel(self.groupBox)
        self.networkSizeLabel.setMinimumSize(QtCore.QSize(150, 22))
        self.networkSizeLabel.setObjectName(_fromUtf8("networkSizeLabel"))
        self.horizontalLayout_5.addWidget(self.networkSizeLabel)
        self.networkSizeLEdit = ParamLineEdit(self.groupBox)
        self.networkSizeLEdit.setMinimumSize(QtCore.QSize(250, 22))
        self.networkSizeLEdit.setObjectName(_fromUtf8("networkSizeLEdit"))
        self.horizontalLayout_5.addWidget(self.networkSizeLEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setMinimumSize(QtCore.QSize(150, 22))
        self.radioButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_4.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setMinimumSize(QtCore.QSize(50, 22))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.oneStepButton = QtGui.QPushButton(self.groupBox)
        self.oneStepButton.setEnabled(True)
        self.oneStepButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.oneStepButton.setObjectName(_fromUtf8("oneStepButton"))
        self.horizontalLayout_6.addWidget(self.oneStepButton)
        self.tenStepsButton = QtGui.QPushButton(self.groupBox)
        self.tenStepsButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tenStepsButton.setObjectName(_fromUtf8("tenStepsButton"))
        self.horizontalLayout_6.addWidget(self.tenStepsButton)
        self.oneHundredStepsButton = QtGui.QPushButton(self.groupBox)
        self.oneHundredStepsButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.oneHundredStepsButton.setObjectName(_fromUtf8("oneHundredStepsButton"))
        self.horizontalLayout_6.addWidget(self.oneHundredStepsButton)
        self.twoHundredStepsButton = QtGui.QPushButton(self.groupBox)
        self.twoHundredStepsButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.twoHundredStepsButton.setObjectName(_fromUtf8("twoHundredStepsButton"))
        self.horizontalLayout_6.addWidget(self.twoHundredStepsButton)
        self.fiveHundredStepsButton = QtGui.QPushButton(self.groupBox)
        self.fiveHundredStepsButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fiveHundredStepsButton.setObjectName(_fromUtf8("fiveHundredStepsButton"))
        self.horizontalLayout_6.addWidget(self.fiveHundredStepsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.menuVLayout.addWidget(self.groupBox)
        self.Simulation = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.Simulation.setObjectName(_fromUtf8("Simulation"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Simulation)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.simSpeedHLayout_2 = QtGui.QHBoxLayout()
        self.simSpeedHLayout_2.setObjectName(_fromUtf8("simSpeedHLayout_2"))
        self.somMapScaleLabel = QtGui.QLabel(self.Simulation)
        self.somMapScaleLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.somMapScaleLabel.setObjectName(_fromUtf8("somMapScaleLabel"))
        self.simSpeedHLayout_2.addWidget(self.somMapScaleLabel)
        self.somMapScaleHSlide = QtGui.QSlider(self.Simulation)
        self.somMapScaleHSlide.setMinimumSize(QtCore.QSize(250, 22))
        self.somMapScaleHSlide.setMinimum(50)
        self.somMapScaleHSlide.setMaximum(300)
        self.somMapScaleHSlide.setProperty("value", 150)
        self.somMapScaleHSlide.setSliderPosition(150)
        self.somMapScaleHSlide.setOrientation(QtCore.Qt.Horizontal)
        self.somMapScaleHSlide.setObjectName(_fromUtf8("somMapScaleHSlide"))
        self.simSpeedHLayout_2.addWidget(self.somMapScaleHSlide)
        self.verticalLayout_2.addLayout(self.simSpeedHLayout_2)
        self.simSpeedHLayout = QtGui.QHBoxLayout()
        self.simSpeedHLayout.setObjectName(_fromUtf8("simSpeedHLayout"))
        self.simSpeedLabel = QtGui.QLabel(self.Simulation)
        self.simSpeedLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.simSpeedLabel.setObjectName(_fromUtf8("simSpeedLabel"))
        self.simSpeedHLayout.addWidget(self.simSpeedLabel)
        self.simSpeedHSlider = QtGui.QSlider(self.Simulation)
        self.simSpeedHSlider.setMinimumSize(QtCore.QSize(250, 22))
        self.simSpeedHSlider.setMinimum(400)
        self.simSpeedHSlider.setMaximum(5000)
        self.simSpeedHSlider.setProperty("value", 530)
        self.simSpeedHSlider.setSliderPosition(530)
        self.simSpeedHSlider.setOrientation(QtCore.Qt.Horizontal)
        self.simSpeedHSlider.setInvertedAppearance(False)
        self.simSpeedHSlider.setInvertedControls(False)
        self.simSpeedHSlider.setObjectName(_fromUtf8("simSpeedHSlider"))
        self.simSpeedHLayout.addWidget(self.simSpeedHSlider)
        self.verticalLayout_2.addLayout(self.simSpeedHLayout)
        self.iterationNumHLayout = QtGui.QHBoxLayout()
        self.iterationNumHLayout.setObjectName(_fromUtf8("iterationNumHLayout"))
        self.iterationNumberLabel = QtGui.QLabel(self.Simulation)
        self.iterationNumberLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.iterationNumberLabel.setObjectName(_fromUtf8("iterationNumberLabel"))
        self.iterationNumHLayout.addWidget(self.iterationNumberLabel)
        self.iterationNumberLEdit = ParamLineEdit(self.Simulation)
        self.iterationNumberLEdit.setEnabled(False)
        self.iterationNumberLEdit.setMinimumSize(QtCore.QSize(250, 22))
        self.iterationNumberLEdit.setAutoFillBackground(True)
        self.iterationNumberLEdit.setReadOnly(True)
        self.iterationNumberLEdit.setObjectName(_fromUtf8("iterationNumberLEdit"))
        self.iterationNumHLayout.addWidget(self.iterationNumberLEdit)
        self.verticalLayout_2.addLayout(self.iterationNumHLayout)
        self.sigmaValueHLayout = QtGui.QHBoxLayout()
        self.sigmaValueHLayout.setObjectName(_fromUtf8("sigmaValueHLayout"))
        self.sigmaLabel = QtGui.QLabel(self.Simulation)
        self.sigmaLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.sigmaLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sigmaLabel.setObjectName(_fromUtf8("sigmaLabel"))
        self.sigmaValueHLayout.addWidget(self.sigmaLabel)
        self.sigmaLEdit = ParamLineEdit(self.Simulation)
        self.sigmaLEdit.setEnabled(False)
        self.sigmaLEdit.setMinimumSize(QtCore.QSize(250, 22))
        self.sigmaLEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sigmaLEdit.setAutoFillBackground(True)
        self.sigmaLEdit.setReadOnly(True)
        self.sigmaLEdit.setObjectName(_fromUtf8("sigmaLEdit"))
        self.sigmaValueHLayout.addWidget(self.sigmaLEdit)
        self.verticalLayout_2.addLayout(self.sigmaValueHLayout)
        self.gammaValHLayout = QtGui.QHBoxLayout()
        self.gammaValHLayout.setObjectName(_fromUtf8("gammaValHLayout"))
        self.gammaLabel = QtGui.QLabel(self.Simulation)
        self.gammaLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.gammaLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gammaLabel.setObjectName(_fromUtf8("gammaLabel"))
        self.gammaValHLayout.addWidget(self.gammaLabel)
        self.gammaLEdit = ParamLineEdit(self.Simulation)
        self.gammaLEdit.setEnabled(False)
        self.gammaLEdit.setMinimumSize(QtCore.QSize(250, 22))
        self.gammaLEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gammaLEdit.setAutoFillBackground(True)
        self.gammaLEdit.setReadOnly(True)
        self.gammaLEdit.setObjectName(_fromUtf8("gammaLEdit"))
        self.gammaValHLayout.addWidget(self.gammaLEdit)
        self.verticalLayout_2.addLayout(self.gammaValHLayout)
        self.pauseButton = QtGui.QPushButton(self.Simulation)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.verticalLayout_2.addWidget(self.pauseButton)
        self.startButton = QtGui.QPushButton(self.Simulation)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.verticalLayout_2.addWidget(self.startButton)
        self.menuVLayout.addWidget(self.Simulation)
        self.horizontalLayoutMain.addLayout(self.menuVLayout)

        self.retranslateUi(QSom)
        QtCore.QMetaObject.connectSlotsByName(QSom)

    def retranslateUi(self, QSom):
        QSom.setWindowTitle(_translate("QSom", "Form", None))
        self.groupBox.setTitle(_translate("QSom", "Parameters", None))
        self.alfaLabel.setText(_translate("QSom", "alfa", None))
        self.gammaZeroLabel.setText(_translate("QSom", "gamma 0", None))
        self.sigmaZeroLabel.setText(_translate("QSom", "sigma 0", None))
        self.networkSizeLabel.setText(_translate("QSom", "network size", None))
        self.label.setText(_translate("QSom", "SOM initial data source", None))
        self.radioButton.setText(_translate("QSom", "Random Generation", None))
        self.radioButton_2.setText(_translate("QSom", "File", None))
        self.label_2.setText(_translate("QSom", "go n iterations forward", None))
        self.oneStepButton.setText(_translate("QSom", "1", None))
        self.tenStepsButton.setText(_translate("QSom", "10", None))
        self.oneHundredStepsButton.setText(_translate("QSom", "100", None))
        self.twoHundredStepsButton.setText(_translate("QSom", "200", None))
        self.fiveHundredStepsButton.setText(_translate("QSom", "500", None))
        self.Simulation.setTitle(_translate("QSom", "Simulation", None))
        self.somMapScaleLabel.setText(_translate("QSom", "SOM map scale", None))
        self.simSpeedLabel.setText(_translate("QSom", "Simulation Speed", None))
        self.iterationNumberLabel.setText(_translate("QSom", "iteration number", None))
        self.sigmaLabel.setText(_translate("QSom", "sigma", None))
        self.gammaLabel.setText(_translate("QSom", "gamma", None))
        self.pauseButton.setText(_translate("QSom", "pause/resume", None))
        self.startButton.setText(_translate("QSom", "START", None))

